In [1]:
!pip install numpy

In [2]:
import numpy as np

# Задание 1

In [30]:
a = int(input())
if a%2!=0:
    a = int(input())
else:
    n = a // 2
    array = np.arange(a)

    array = array.reshape(n, 2)
    one_col = np.ones((n, 1))

    ans = np.hstack((one_col, array))
    print(ans)




8
[[1. 0. 1.]
 [1. 2. 3.]
 [1. 4. 5.]
 [1. 6. 7.]]


# Задание 2

In [53]:
v ='1, 2, 3, 4, 5.0, 6, 7, 8, 9, 10'
v1 = np.array(v)
print(v1)
print(type(v1))

v1 = np.array([float(x.strip()) for x in v.split(',')])
print(v1)

v2 = np.array([v1[-2]])
print(v2)

v3 = v1[::-1]
print(v3)

v4 = v1[len(v1)-2: 0: -3]
print(v4)

v5 = np.arange(len(v.split(',')))
print(v5)

1, 2, 3, 4, 5.0, 6, 7, 8, 9, 10
<class 'numpy.ndarray'>
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[9.]
[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]
[9. 6. 3.]
[0 1 2 3 4 5 6 7 8 9]


# Задание 3


In [56]:
a = '1, 2, 3, 4'
b = '10, 20, 30, 40'

v1 = np.array([float(x.strip()) for x in a.split(',')])
v2 = np.array([float(x.strip()) for x in b.split(',')])

v3 = v1 + v2
print(v3)

# V4 Numpy вектор с покоординатными произведениями каждого второго числа V1 на каждое второе число V2, развёрнутого в обратном порядке
v4 = v1[1::2] * ( v2[1::2][::-1] )
print(v4)

[11. 22. 33. 44.]
[80. 80.]


# Задание 4


In [58]:
n = int(input("размер Numpy вектора "))
x = int(input("координата элемента вектора "))

z = np.zeros(n)
z[x] = 1

print(z)


размер Numpy вектора 4
координата элемента вектора2
[0. 0. 1. 0.]


# Задание 5

In [59]:
n = int(input("размер Numpy вектора "))
x = int(input("координата элемента вектора "))

z = np.zeros(n)
z[x] = 1

print(z[::-1])


размер Numpy вектора 4
координата элемента вектора 2
[0. 1. 0. 0.]


# Задание 6

In [61]:
n = int(input("размер единичной матрицы "))

ones = np.ones(n)

z = ones
print(z)

размер единичной матрицы 4
[1. 1. 1. 1.]


# Задание 7

In [70]:
n = int(input("размер матрицы "))
m = int(input("размер матрицы "))

matr = np.zeros((n, m))

matr[0] = 1
matr[n - 1] = 1
matr[:, 0] = 1
matr[:, m - 1] = 1

print(matr)

размер матрицы 10
размер матрицы 6
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]
